# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b593ef3c8b7f26579b456b4d656ed5219a1a98071578f4cc42a9926e6b4c28d53f31ffe930986dc41e7b9044af7e2a61e43b05369c6a77114ec7cf3fcebeb407

test:
  secret_key_base: ca6470469065196f2906fb9fe7f108a82eca98e2b9674230f46bdb8b71e4152d61f7ed9ba0284452c2ac1f19057857a8af783bf91d95f1e370382b8457c3e94b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
